name: CI

on:
  push:
    branches: 
    - main
    - Dev
    - Features/*
    - refactor
  pull_request:
    branches:
    - main
    - Dev
    - Features/*
    - refactor
  pull_request_target:
    branches:
    - main
    - Dev
    - Features/*
    - refactor
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/evoKnowledgeShare
    - name: Build
      run: dotnet build --configuration Release
      working-directory: src/evoKnowledgeShare
    - name: Test with the dotnet CLI
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: src/evoKnowledgeShare
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: src/evoKnowledgeShare/coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '75 90'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request_target'
      with:
        recreate: true
        path: code-coverage-results.md
